(lang dune 3.5)

(name mandelbrot)

; break @ dune__exe__Main LINE_NUM
; Or setting `wrapped_executables` to `false` allows this shorter form
; break @ Main LINE_NUM

(wrapped_executables false)

(package
 (name mandelbrot))
